// JavaScript Document
/*
 

 Panorado JS - Panoramic Viewer for HTML5
 (c) 2012-2014 by Karl Maloszek - Simple Software
 http://www.panorado.com/en/PanoradoJs.php
 Use is free on private (non-commercial) websites.
 This is not public domain software!
 Comments are welcome.

*/
function PanoradoJS(mb){var Pb,mc,Qb,ma,ua,Ea,Fa,$a,ab,w,nb,nc,va,bb,Ga,Ha,cb,T,db,da,U,oc,ob,pb,wa,eb,qb,Ia,Rb,na,Ja,Sb,Tb,xa,Y,Ka,pc;function Ub(){K();var a="-- Viewer:\nPanorado JS v. "+Pb+"\n"+mc+"\n("+Qb+")\n\n",a=a+("-- Browser:\n"+navigator.appName+"\n"+navigator.appVersion+"\n"+navigator.platform+"\n"+navigator.userAgent+"\n\n"),a=a+"-- WebGL graphics:\n",a=h?h.ctx?a+("Version: "+h.ctx.getParameter(h.ctx.VERSION)+"\nVendor: "+h.ctx.getParameter(h.ctx.VENDOR)+"\nRenderer: "+h.ctx.getParameter(h.ctx.RENDERER)+
"\nShading language version: "+h.ctx.getParameter(h.ctx.SHADING_LANGUAGE_VERSION)+"\nMax. texture size: "+h.ctx.getParameter(h.ctx.MAX_TEXTURE_SIZE)+"\n\n"):a+"Drawing context not available\n\n":a+"Currently not used\n\n",a=a+"-- Device capabilities:\n",a=a+("Touch: "+(ya||za)+" (currently "+(ea?"":"not")+" used)\nOrientation: "+(G?!0:!1)+" (currently "+(G&&"none"!=G.usrMode?"":"not")+" used)");l();setTimeout(function(){alert(a)},0)}function V(){return b&&b.video?!0:!1}function I(){return b&&b.video&&
b._type==ma?!0:!1}function rb(){return b&&b._type==ma&&b.video&&!b.video.ended&&!b.video.paused?!0:!1}function sb(){return b&&b._type==Ea?!0:!1}function Vb(){if(I())b.video.currentTime=0,b.video.play();qc(null)}function Wb(){if(b)u=b.pan,q=b.tilt,tb(),j=La(b.scale),W=Q=fb=fa=n=m=0,ga=!1,L=A=0,M=Date.now()}function K(){Aa&&(clearTimeout(Aa),Aa=0);W=fa=n=m=0;L=Date.now()}function v(){return B==Fa}function rc(a){ha&&(0>a?a=0:a>=ha.length-1&&(a=ha.length-1),a!==Z&&(Xb(ha[a]),Z=a))}function Yb(a){rc(Z+
a)}function Xb(a){a?qc(a):(ia(),Zb(null))}function Zb(a){B=$a;if(V())b.video.oncanplay=null,I()&&b.video.pause();b=void 0;if(a){var g=ab,d=null;if(a.type)switch(a.type){case "cubefile":g=Ea;break;case "videofile":g=ma;break;case "livestream":g=ua}if(g!=ua&&!a.src)Z=-1,l();else{var c=null,f=null;b={};switch(g){case ab:c=sc(a.src);d="imagefile";break;case Ea:c=sc(a.src);d="cubefile";break;case ma:var p=a.src,d=a.loop;B=va;f=document.createElement("video");f.onerror=Ba;f.oncanplay=Pc;f.style.display=
"none";for(var p=p.split(";"),z=null,x=0;x<p.length;x++){var e=null;if(p[x].match(/\S.mp4$/i))e="video/mp4";else if(p[x].match(/\S.webm$/i))e="video/webm";else if(p[x].match(/\S.ogg$/i)||p[x].match(/\S.ogv$/i))e="video/ogg";if(e&&f.canPlayType(e)){z=p[x];break}}f.src=z;if(d)f.loop=!0;if(f)a.src=f.src;d="videofile";break;case ua:f=Qc(),d="livestream"}b._type=g;b.type=d;b.img=c;b.video=f;b.src=a.src;b.title=a.title?a.title:"";b.description=a.description?a.description:"";b._projection=a.projection&&
"spherical"==a.projection?w:nb;C=b._projection;b.projection="spherical"==a.projection?"spherical":"flat";b.horizon=a.horizon?N(Number(a.horizon),-45,45):0;b.pan=a.pan?Number(a.pan):0;b.tilt=a.tilt?Number(a.tilt):0;b.scale="number"==typeof a.scale?Number(a.scale):1;g=Number(a.horzFov);b.horzFov=0<g&&360>g?g:360;b.vertFov=0;b.is360=360==b.horzFov;b.panSpeed=V()?0:nc;b.tiltSpeed=0;if(null!=a.panSpeed)b.panSpeed=N(Number(a.panSpeed),-da,da);if(a.tiltSpeed)b.tiltSpeed=N(Number(a.tiltSpeed),-da,da);Na=
a.compassNorth?!0:!1;b.compassNorth=a.compassNorth?Number(a.compassNorth):0;b.compassNorth+=3600;b.compassNorth%=360;b._loop=a.loop&&"true"==a.loop?!0:!1;$=[];oa=null;if(a=a.hotspots)for(g=0;g<a.length;g++)$.push(new Rc(a[g]));b.hotspots=$;X.create();O()}}else Z=-1,l()}function sc(a){B=va;var b=new Image;b.onload=ub;b.onerror=Ba;b.onabort=Ba;b.src=a;return b}function Pc(a){a=a.target;a.videoWidth&&a.videoHeight?(a.width=a.videoWidth,a.height=a.videoHeight,ub(),a.play()):Ba()}function tc(){rb()?b.video.pause():
b.video.play()}function uc(){if(I())return b.video.muted?!1:!0}function Qc(){B=va;var a=document.createElement("video");navigator.getMedia=navigator.getUserMedia||navigator.webkitGetUserMedia||navigator.mozGetUserMedia||navigator.msGetUserMedia;if(!navigator.getMedia)return setTimeout(Ba,0),a;navigator.getMedia({video:{mandatory:{minWidth:$b}},audio:!1},function(b){a.oncanplay=Sc;var d=window.URL||window.webkitURL;a.src=d?d.createObjectURL(b):b;a.play()},function(a){Ba();console.log("navigator.getMedia error: "+
a.name+" "+a.message)});return a}function Sc(a){function b(){d.videoWidth&&d.videoHeight?(d.width=d.videoWidth,d.height=d.videoHeight,ub()):20>c++?setTimeout(b,200):Ba()}var d=a.target,c=1;b()}function Ba(){B=bb;ia();l();Oa&&setTimeout(Oa,0)}function ub(){if(b&&!v()){B=Fa;if(V())b.width=b.video.width,b.height=b.video.height;else if(sb()){if(!h||b.img.width!=6*b.img.height){B=bb;l();return}b.width=b.img.height*Math.PI;b.height=b.width/2}else b.width=b.img.width,b.height=b.img.height;if(sb())b.horzFov=
360,b.vertFov=180;else if(b.vertFov=b.horzFov*b.height/b.width,180<b.vertFov)b.horzFov*=180/b.vertFov,b.vertFov=180;b.is360=360==b.horzFov;b.scale=La(b.scale);b.pan=Pa(b.pan);b.tilt=Qa(b.tilt);vb();Wb();O();vc=!1;l();Oa&&setTimeout(Oa,0)}}function qc(a){ia();K();if(b){if(h)h.canvas.style.background="transparent";wb=!0;wc();wb=!1}else if(h&&h.canvas)h.canvas.style.background="#000";if(e.dataUrl){E=new Image;E.onload=function(){if(E){E.style.position="absolute";E.style.left=e.canvas.offsetLeft+e.canvas.clientLeft+
"px";E.style.top=e.canvas.offsetTop+e.canvas.clientTop+"px";E.width=e.canvas.clientWidth;E.height=e.canvas.clientHeight;ac=!0;a?Zb(a):(Wb(),xb());var d=h&&C==w?h.canvas:e.canvas;d.parentNode.insertBefore(E,d);E.style.zIndex=Number(d.style.zIndex)}};try{E.src=e.dataUrl,delete e.dataUrl}catch(g){ia()}}else a?Zb(a):(Wb(),xb())}function ia(){wb=!1;E&&ac&&(E.parentNode&&E.parentNode.removeChild(E),E=void 0,ac=!1);e.dataUrl&&delete e.dataUrl;A=1}function gb(a,b){xc(u+a,q+b,null)}function xc(a,b,d){M=0;
K();ga=!1;v()&&("number"==typeof d&&(j=La(d)),u=a,q=b,l())}function Ca(a){ga=!1;P(j*a)}function P(a){K();v()&&(0!=pa?(fb=j,Q=La(a),Q!=j&&(W=Date.now())):(a=La(a),j!=a&&(bc(j,a),j=a)),l())}function tb(){var a=yc();qa=Math.max(Ga,cc);qa=Math.max(qa,a);Ra=Math.min(Ha,dc);Ra=Math.max(Ra,qa)}function La(a){Sa=!1;if("number"!=typeof a||0==a)a=yc(),Sa=!0;else if(a<qa)a=qa;else if(a>Ra)a=Ra;else for(var b=[0.125,0.125*Math.SQRT2,0.25,0.25*Math.SQRT2,0.5,0.5*Math.SQRT2,1,1*Math.SQRT2,2,2*Math.SQRT2,4,4*Math.SQRT2,
8],d=0;d<b.length;d++)if(a>0.999*b[d]&&a<1.001*b[d]){a=b[d];break}return a}function yc(){if(!v())return 0;var a=b.width,g=b.height,d=e.canvas.width,c=e.canvas.height;if(C==w){var f;f=Math.min(b.horzFov,cb)/2;d*=f*T/ra(f);f=Math.min(b.vertFov,db)/2;c*=f*T/ra(f);a=Math.min(a*cb/b.horzFov,a);g=Math.min(g*db/b.vertFov,g)}return Math.min(d/a,c/g)}function F(a,b){M=0;K();ga=!1;v()&&(null!==a&&(m=N(a,-da,da)),null!==b&&(n=N(b,-da,da)),L=Date.now(),l())}function Pa(a){if(b.is360)a=(a+36E3)%360;else{var g=
e.canvas.width/b.width*b.horzFov/j;C==w?(g=2*Math.atan(g*T/2)*U,g=Math.min(g,cb)):g=Math.min(g,b.horzFov);var g=g/2,d=b.horzFov-g;g>d?a=b.horzFov/2:a<g?a=g:a>d&&(a=d)}return a}function Qa(a){var g;e.canvas?(g=e.canvas.height/b.height*b.vertFov/j,C==w?(g=2*Math.atan(g*T/2)*U,g=Math.min(g,db)):g=Math.min(g,b.vertFov)):g=0;var d=(b.vertFov-g)/2,c=-d,d=d-b.horizon,c=c-b.horizon;C==w&&b.is360&&(90<=b.vertFov/2-b.horizon&&(d+=g/2),90<=b.vertFov/2+b.horizon&&(c-=g/2));d<c?a=(c+d)/2:a<c?a=c:a>d&&(a=d);return a}
function bc(a,b){if(ga){var d=Da(a),c=Da(b);u+=d.x-c.x;q+=d.y-c.y}d=j;j=b;u=Pa(u);q=Qa(q);j=d;0==W&&(ga=!1)}function Da(a,g,d,c,f){a||(a=j);if(void 0==g)g=i.x;if(void 0==d)d=i.y;void 0==c&&(c=u);void 0==f&&(f=q);g-=e.canvas.width/2;d=-(d-e.canvas.height/2);if(C==w)var p=b.width/b.horzFov*a*U,a=p*R(f)-d*ja(f),f=p*ja(f)+d*R(f),c=c+Ta(g,a),f=Ta(f,aa(g,a));else c+=g/a*b.horzFov/b.width,f+=d/a*b.vertFov/b.height;b.is360&&(0>c?c+=360:360<c&&(c-=360));return new yb(c,f)}function hb(a,g){var d,c;if(C==w){d=
b.width/b.horzFov*j*U;c=d*R(q)-g*ja(q);var f=d*ja(q)+g*R(q);d=Ta(a,c);c=Ta(f,aa(a,c))}else d=a/j*b.horzFov/b.width,c=q+g/j*b.vertFov/b.height;b.is360&&(0>d?d+=360:360<d&&(d-=360));return new yb(d,c)}function zc(a,g){var d,c;d=a-u;b.is360&&(-180>=d?d+=360:180<d&&(d-=360));if(C==w){var f=b.width/b.horzFov*j*U,p=Ta(ra(g),R(d));c=p-q;if(-90>=c||90<c)return null;var z=f/R(c),p=R(p)*z;d=ra(d)*p;c=ra(c)*f}else c=g-q,d=d/b.horzFov*b.width*j,c=c/b.vertFov*b.height*j;return new yb(e.canvas.width/2+d,e.canvas.height/
2-c)}function l(a){var g=Tc();!a||g||b&&b.video&&(b._type==ua||b._type==ma&&!b.video.ended&&!b.video.paused)?(a=10,rb()&&(a=C==w?100:50),setTimeout(function(){wc();xb()},a),O()):xb();g&&zb&&setTimeout(zb,0)}function Ab(){l(!0)}function xb(){if(m||n||M||fa||W||V())oc?Uc(Ab):(Aa&&(clearTimeout(Aa),Aa=0),Aa=window.setTimeout(Ab,10))}function Tc(){if(!v())return!1;var a=L,b=u,d=q,c=j;L=Date.now();var f;f=0|Vc();f|=Wc();i.isDragging()&&ka?f=!0:(a=(L-a)/1E3,u+=m*a,q+=n*a);var p,z,x,e,a=j;0==W||Q==fb||(p=
1+(L-W)/(500*(2<<pa)),z=Math.log(fb),x=Math.log(Q),e=Math.log(j),z=1+Math.min(2*Math.abs(z-e),Math.abs(x-e)+(x-e)*(x-e))/Math.abs(z-x)/16,p*=z,fb<Q?(a*=p,a>Q&&(a=Q)):(a/=p,a<Q&&(a=Q)),a==Q?(j=a,W=0):W=L);bc(j,a);j=a;f|=b!=u;f|=d!=q;f|=c!=j;return f|=Ac()}function Vc(){var a=1E3*ec;if(v()){if(0==M)return ia(),!1;if(L<M+a){var g=A;A=(L-M)/a;return A!=g}if(0==b.panSpeed&&0==b.tiltSpeed)return ia(),M=0,!0;if(b.panSpeed!=m||b.tiltSpeed!=n){ia();if(G&&G.mode!=ob)m=n=0;else{a=(L-M-a-2E3)/4E3;if(0>a)return!0;
m=a*b.panSpeed;n=a*b.tiltSpeed;m=0<b.panSpeed?Math.min(b.panSpeed,m):Math.max(b.panSpeed,m);n=0<b.tiltSpeed?Math.min(b.tiltSpeed,n):Math.max(b.tiltSpeed,n)}return!0}ia();M=0;return!1}A=0;return!1}function Wc(){if(0==fa||fa==L)return!1;if(aa(m,n)>0.02/j*b.horzFov/90){var a=1-(L-fa)/(25*(2<<Bb));if(0<a)return m*=a,n*=a,fa=L,!0}m=n=fa=0;return!0}function wc(){if(e.ctx&&(B!=va||vc)){e.ctx.clearRect(0,0,e.canvas.width,e.canvas.height);Cb()?(h.ctx.clearColor(0,0,0,A),h.ctx.clear(h.ctx.COLOR_BUFFER_BIT)):
(h&&h.ctx&&!E&&(h.ctx.clearColor(0,0,0,1),h.ctx.clear(h.ctx.COLOR_BUFFER_BIT)),e.ctx.globalAlpha=A,e.ctx.fillStyle="#000",e.ctx.fillRect(0,0,e.canvas.width,e.canvas.height));switch(B){case $a:sa("");break;case va:switch(b._type){case ab:case Ea:sa("Loading image '"+b.src+"'...");break;case ma:sa("Loading video '"+b.src+"'...");break;case ua:sa("Opening live stream...")}break;case bb:switch(b._type){case ab:case Ea:sa("Error loading image file '"+b.src+"' !");break;case ma:sa("Error loading video file '"+
b.src+"' !");break;case ua:sa("Error opening user media live stream!")}break;case pb:sa("WebGL error: Context lost!");break;case Fa:var a=e.canvas.width,g=e.canvas.height,d;e.canvas?(C==w?(d=Math.min(b.horzFov,cb),d=2*ra(d/2)/(b.horzFov*T)*b.width*j):d=b.width*j,d=Math.round(Math.min(d,e.canvas.width))):d=0;var c;C==w?(c=Math.min(b.vertFov,db),c=2*ra(c/2)/(b.vertFov*T)*b.height*j):c=b.height*j;c=Math.round(Math.min(c,e.canvas.height));a=Math.round((a-d)/2);g=Math.round((g-c)/2);d=a+d;c=g+c;C==w?Cb()?
(Date.now(),h.paint(a,g,d,c)):(Date.now(),e.paintSpherical(a,g,d,c)):(Date.now(),e.paintFlat(a,g,d,c));Date.now();if(ba&&$){e.ctx.save();e.ctx.globalAlpha=A;for(var f=0;f<$.length;f++){var p=$[f];p.paint();!ea&&p.isUnderCursor()&&(oa=p)}e.ctx.restore()}if(!h&&C==w&&B==Fa){f=e.ctx;f.save();f.setTransform(1,0,0,1,0,0);f.globalAlpha=A;f.fillStyle="#000";var p=mb.width,z=mb.height;0<a&&f.fillRect(0,0,a,z);d<p&&f.fillRect(d,0,d,z);0<g&&f.fillRect(a,0,d-a,g);c<z&&f.fillRect(a,c,d-a,z-c);f.restore()}if(Na)if(C==
w)g=e.canvas.width/2,d=(u-b.compassNorth+3600)%360,Bc(d,g);else{a=50/j*(b.horzFov/b.width);g=[1,2,5,10,15,30,45,90];for(d=0;d<g.length;d++)if(a<=g[d]||d==g.length-1){a=g[d];break}c=u-e.canvas.width/2/j*b.horzFov/b.width;c-=b.compassNorth;c=Math.round(c/a)*a;for(c=c-a+b.compassNorth;(g=j*b.width/b.horzFov*(c-u)+e.canvas.width/2)<e.canvas.width;)d=(c-b.compassNorth+36E3)%360,Bc(Math.round(d),g),c+=a}fc&&X.paint();oa&&1==A&&oa.paintPopup()}if(wb)try{var x=Cb()?h.canvas:e.canvas;e.dataUrl=x.toDataURL("image/png")}catch(Ma){e.dataUrl=
null}}}function sa(a){var b=e.canvas,d=e.ctx;d.globalAlpha=1;var c="",c=b.style.fontStyle?c+(b.style.fontStyle+" "):c+"italic ";b.style.fontVariant&&(c+=b.style.fontVariant+" ");b.style.fontWeight&&(c+=b.style.fontWeight+" ");c=b.style.fontSize?c+(b.style.fontSize+" "):c+"12px ";c=b.style.fontFamily?c+b.style.fontFamily:c+wa;d.font=c;d.fillStyle="#dd0";d.textBaseline="top";d.fillText(a,15,15)}function Bc(a,b){var a=Math.round(a),d=Xc(a),c=0==a%90,f=e.ctx;f.save();f.globalAlpha=A;f.font=(c?"16px":
"12px")+" "+wa;f.textBaseline="bottom";f.lineWidth=3.5;f.fillStyle=c?"#ff0":"#fff";f.strokeStyle="#333";f.beginPath();f.textBaseline="top";f.rect(b,0,1.5,12);f.stroke();f.fill();f.strokeText(d,b+5,1);f.fillText(d,b+5,1);f.restore()}function Xc(a){switch(a){case 0:case 360:return"N";case 90:return"E";case 180:return"S";case 270:return"W";default:return ib(a,3)}}function Ac(){var a=X.mouseOver();if(gc!=a)return gc=a,!0;a=hc();return fc!=a?(fc=a,!0):!1}function hc(){return!ca||!X.visible?!1:0<=i.x&&
i.x<e.canvas.width&&0<=i.y&&i.y<e.canvas.height}function Yc(a){a.imgInfo?(s.imgInfo=new Image,s.imgInfo.onload=function(){l()},s.imgInfo.onerror=function(){s.imgInfo=null},s.imgInfo.src=a.imgInfo):s.imgInfo=Db(!1);a.imgLink?(s.imgLink=new Image,s.imgLink.onload=function(){l()},s.imgLink.onerror=function(){s.imgLink=null},s.imgLink.src=a.imgLink):s.imgLink=Db(!0);s.border=!0===a.border;s.shadow=!0===a.shadow;s.opacity="number"==typeof a.opacity?a.opacity:1;s.opacity=N(s.opacity,0,1)}function ic(){if(!ba||
!$)return null;for(var a=0;a<$.length;a++){var b=$[a];if(b&&b.isUnderCursor())return b}return null}function Db(a){var b=document.createElement("canvas"),d=b.width=b.height=96,c=b.getContext("2d");c.setTransform(1,0,0,1,48,48);c.beginPath();c.arc(0,0,d/2-2,0,2*Math.PI,!1);c.lineWidth=2;var f=c.createLinearGradient(0,-d/2,0,d/2);f.addColorStop(0,"#f88");f.addColorStop(1,"#a00");c.fillStyle=f;c.stroke();c.fill();c.beginPath();c.arc(0,0,0.4*d,0,2*Math.PI,!1);c.fillStyle="#f00";c.fill();c.strokeStyle=
c.fillStyle="#fff";c.lineCap="round";c.lineJoin="round";c.lineWidth=7;c.shadowBlur=4;c.shadowColor="#444";a?(c.beginPath(),c.moveTo(-15,-15),c.lineTo(15,0),c.lineTo(-15,15)):(c.beginPath(),c.moveTo(-12,-4),c.lineTo(0,-4),c.lineTo(0,20),c.moveTo(-14,20),c.lineTo(14,20),c.stroke(),c.beginPath(),c.arc(-2,-20,2.5,0,2*Math.PI,!1));c.stroke();return b}function Cc(a){a?h||(h=new Dc,!h.canvas||!h.ctx?h=void 0:vb()):h&&!sb()&&(h.clearBuffers(),h.canvas.parentNode&&h.canvas.parentNode.removeChild(h.canvas),
h=null);jb();l();O()}function Cb(){return h&&C==w&&B==Fa}function vb(){Cb()?h.setBuffers():h&&h.clearBuffers()}function ta(a){if(e.canvas&&a)e.canvas.style.cursor="url("+a+"),move",e.canvas.width=e.canvas.width}function O(){if(!e.canvas||ea)e.canvas.style.cursor="auto";else{var a;B==$a||B==bb?a="auto":B==va?a="wait":ca?!i.isDragging()&&X.getFunctionUnderCursor()?a="pointer":(a=ic())&&a.isLink()?a="pointer":(a=ka?i.isDragging()?Eb:Fb:i.isDragging()?Gb:Hb,a=(a?"url("+a+"),":"")+"move"):a="auto";e.canvas.style.cursor=
a}}function Ec(a){K();e.canvas.removeEventListener("touchstart",Ua,!0);document.removeEventListener("touchend",Va,!0);document.removeEventListener("touchmove",Wa,!0);e.canvas.removeEventListener("pointerdown",Ua,!0);document.removeEventListener("pointerup",Va,!0);document.removeEventListener("pointermove",Wa,!0);e.canvas.removeEventListener("mousedown",Ua,!0);document.removeEventListener("mouseup",Va,!0);document.removeEventListener("mousemove",Wa,!0);e.canvas.removeEventListener("mousewheel",Ib,
!0);e.canvas.removeEventListener("DOMMouseScroll",Ib,!1);(ea=a&&(ya||za))?ya?(e.canvas.addEventListener("touchstart",Ua,!0),document.addEventListener("touchend",Va,!0),document.addEventListener("touchmove",Wa,!0)):za&&(e.canvas.addEventListener("pointerdown",Ua,!0),document.addEventListener("pointerup",Va,!0),document.addEventListener("pointermove",Wa,!0)):(e.canvas.addEventListener("mousedown",Ua,!0),document.addEventListener("mouseup",Va,!0),document.addEventListener("mousemove",Wa,!0),e.canvas.addEventListener("mousewheel",
Ib,!0),e.canvas.addEventListener("DOMMouseScroll",Ib,!1));l()}function J(a){a.preventDefault();a.stopPropagation()}function Jb(a){return window.mozAnimationStartTime?window.mozAnimationStartTime:a.timeStamp}function Zc(){}function $c(){}function ad(a){if(ca&&v()&&!i.isDragging()){switch(a.which){case 37:case 177:a.shiftKey?F(m-eb,null):(F(0,0),gb(-1/Math.sqrt(j),0));break;case 39:case 176:a.shiftKey?F(m+eb,null):(F(0,0),gb(1/Math.sqrt(j),0));break;case 38:a.shiftKey?F(null,n+eb):(F(0,0),gb(0,1/Math.sqrt(j)));
break;case 40:a.shiftKey?F(null,n-eb):(F(0,0),gb(0,-1/Math.sqrt(j)));break;case 13:kb&&Kb(!0);break;case 27:m||n?F(0,0):kb&&Xa&&Kb(!1);break;case 178:F(0,0);break;case 179:I()?tc():Vb();break;case 107:case 187:case 175:a.ctrlKey||(a.shiftKey?Ca(qb):Ca(Ia));break;case 109:case 189:case 174:a.ctrlKey||(a.shiftKey?Ca(1/qb):Ca(1/Ia));break;case 49:case 97:P(1);break;case 50:case 98:P(2);break;case 53:case 101:P(0.5);break;case 65:P(0);break;case 77:ka=!ka;O();break;case 67:Na=!Na;l();break;case 72:ba=
!ba;l();break;case 73:Ub();break;default:return}J(a)}}function Ua(a){ca&&v()&&(a.which&&1!=a.which?i.clear():a.shiftKey||a.ctrlKey||a.altKey?i.clear():a.target!=e.canvas?i.clear():(i.setEvent(a),J(a),document.activeElement==e.canvas||e.canvas.focus(),jc(),W=M=0,A=1,a=X.getFunctionUnderCursor(),null!==a?(i.clear(),gc=-1,"function"===typeof a&&window.setTimeout(a,0)):(K(),l())))}function Va(a){if(ca&&v()){if(!(a.which&&1!=a.which)){var b=i.time;i.setEvent(a);if(i.isDragging()){J(a);var d=ea?12:2,c=
i.getDragDist()<=d;O();if(c){var f=oa,p=ic();oa=p;if(f||p)if(ea){if(f&&f.isLink()&&f.isPopupUnderCursor()){i.clear();f.gotoUrl();m=n=0;l();return}}else if(p&&p.isLink()&&p.isUnderCursor()){i.clear();p.gotoUrl();m=n=0;l();return}l()}ka&&(b=Math.max((Date.now()-b-100)/-100,0),m*=b,n*=b);0!=Bb&&(0!=m||0!=n)?fa=Date.now():m=n=0;i.time=Jb(a);la&&clearTimeout(la);if(c&&(Lb||lb))la?(la=0,lb&&aa(i.x-Fc,i.y-Gc)<d&&setTimeout(lb,0)):(Fc=i.xDown,Gc=i.yDown,la=setTimeout(function(){la=0;Lb()},500))}}i.clear()}}
function Wa(a){if(ca&&v())if(a.which&&1!=a.which)i.clear();else if(!(void 0!=a.webkitMovementX&&!a.webkitMovementX&&!a.webkitMovementY)){var g=Jb(a);if(!Hc||!(g&&g<Date.now()-10)){var d=i.x,c=i.y,g=g-i.time;i.setEvent(a);if(i.isPinchZooming())J(a),jc(),c=i.startScale,d=i.getPinchScale(),c=Da(c,i.xDown,i.yDown),a=Da(d,i.x,i.y),u=i.startPan+c.x-a.x,q=i.startTilt+c.y-a.y,j=d,u=Pa(u),q=Qa(q),Ab();else if(i.isDragging()){J(a);jc();if(la){clearTimeout(la);la=0;return}a=b.horzFov/b.width/j;if(ka){var f=
Da(i.startScale,i.xDown,i.yDown,i.startPan,i.startTilt),p,z=j;p=f.x;var x=f.y,f=i.x-e.canvas.width/2,Ma=-(i.y-e.canvas.height/2);if(C==w){var S=b.width/b.horzFov*z*U,z=aa(S,Ma),Ma=Ta(Ma,S),k=aa(f,z),S=ja(x)*k,x=R(x)*k,x=Math.asin(f/x)*U;isNaN(x)&&(x=0<f?90:-90);p-=x;f=Math.acos(S/z)*U;isNaN(f)&&(f=0<S?0:180);f=90-f-Ma}else p-=f/z*b.horzFov/b.width,f=x-Ma/z*b.vertFov/b.height;p=new yb(p,f);u=Pa(p.x);q=Qa(p.y);m/=a;n/=a;m/=2;n/=2;10>g&&(g=10);m+=500*((d-i.x)/g);n-=500*((c-i.y)/g);m*=a;n*=a}else d=i.getDragDistX(),
c=i.getDragDistY(),m=d*Math.max(Math.abs(d),100)*Rb*a,n=-c*Math.max(Math.abs(c),100)*Rb*a;Ab();Mb&&setTimeout(Mb,0)}else Ac()?l():ea||(d=ic(),d!=oa&&(oa=d,l()));O()}}}function Ib(a){if(ca&&v()&&!kc&&!i.isDragging()&&!a.ctrlKey&&!a.altKey&&!(a.mozInputSource&&a.mozInputSource==a.MOZ_SOURCE_TOUCH)&&!(null!=a.axis&&a.axis==a.HORIZONTAL_AXIS)&&!(null!=a.wheelDeltaY&&0==a.wheelDeltaY)&&!(null!=a.wheelDelta&&1E4<Math.abs(a.wheelDelta))){var b=a.shiftKey?qb:Ia;e.canvas.focus();i.setEvent(a);var d=0<=(a.detail?
-120*a.detail:a.wheelDelta);lc&&(d=!d);var c=0==W?j:Q,b=c*(d?b:1/b);0==pa&&bc(c,b);M=0;K();ga=!0;P(b);J(a)}}function jc(){document.selection?document.selection.empty():window.getSelection&&window.getSelection().removeAllRanges()}function Ic(a){if(ca&&v()&&G){var g=Jb(a);if(!Hc||!(g&&Date.now()-10>g)){G.newEvent(a);var d=G.pan,c=G.tilt;switch(G.mode){case na:d+=b.compassNorth;d%=360;setTimeout(function(){K();u=Pa(d);q=Qa(c);l()},0);break;case Ja:var c=c+60,d=3<d?d-3:-3>d?d+3:0,c=3<c?c-3:-3>c?c+3:0,
f=0.5*d*Math.abs(d),p=0.5*c*Math.abs(c);ka&&(f*=-1,p*=-1);M=0;setTimeout(function(){F(f,p)},0)}}}}function Jc(a){if(pc){var b=document.getElementById("debug1");if(b)b.innerHTML="_onCompassNeedsCalibration"}J(a)}function bd(){console.log("Panorado JS: WebGL context lost - trying to restore WebGL!");l();Cc(!0)}function cd(){console.log("Panorado JS: WebGL context restored!");B=pb;ub();l()}function Kc(a,b){if(e.canvas){ia();e.canvas.width=a;e.canvas.height=b;if(e.canvas.style.width&&e.canvas.style.width.match(/px$/))e.canvas.style.width=
a+"px";if(e.canvas.style.height&&e.canvas.style.height.match(/px$/))e.canvas.style.height=b+"px";if(e.canvas&&h&&h.canvas){var d=h.canvas.style;d.zIndex=e.canvas.style.zIndex;d.position="absolute";d.left=e.canvas.offsetLeft+e.canvas.clientLeft+"px";d.top=e.canvas.offsetTop+e.canvas.clientTop+"px";d.width=a+"px";d.height=b+"px";h.canvas.width=e.canvas.clientWidth;h.canvas.height=e.canvas.clientHeight;h.canvas.parentNode!=e.canvas.parentNode&&(h.canvas.parentNode.removeChild(h.canvas),e.canvas.parentNode.insertBefore(h.canvas,
e.canvas))}d=pa;pa=0;tb();P(Sa?0:j);pa=d;l(!0)}}function jb(){Kc(e.canvas.clientWidth,e.canvas.clientHeight)}function Kb(a){if(e.canvas&&a!=Xa){if(h&&h.canvas)h.canvas.style.visibility="hidden";if(Xa=a){if(a=document.body.style,document.body.oldStyleText=document.body.style.cssText,a.overflow="hidden",a=e.canvas.style,e.canvas.oldStyleText=e.canvas.style.cssText,a.position="absolute",a.left="0",a.top="0",a.margin="0",a.width="100%",a.height="100%",a.border="none",a.borderRadius="0",a.zIndex=9999,
document.documentElement.scrollLeft=0,document.documentElement.scrollTop=0,document.body.scrollLeft=0,document.body.scrollTop=0,e.canvas.parentNode!=document.body)e.canvas.oldParentNode=e.canvas.parentNode,e.canvas.placeholder=document.createElement("placeholder"),e.canvas.parentNode.replaceChild(e.canvas.placeholder,e.canvas),document.body.appendChild(e.canvas)}else{if(e.canvas.oldParentNode)e.canvas.parentNode.removeChild(e.canvas),e.canvas.oldParentNode.replaceChild(e.canvas,e.canvas.placeholder),
e.canvas.oldParentNode=null,delete e.canvas.placeholder;if(e.canvas.oldStyleText)e.canvas.style.cssText=e.canvas.oldStyleText,delete e.canvas.oldStyleText;if(document.body.oldStyleText)document.body.style.cssText=document.body.oldStyleText,delete document.body.oldStyleText}jb()}}function Uc(a){(window.requestAnimationFrame||window.webkitRequestAnimationFrame||function(a){window.setTimeout(a,0)})(a)}function ib(a,b){for(var d="",c=Math.pow(10,b-1);a<c&&1<c;)d+="0",c/=10;return d+a}function Dc(){function a(a,
b){var f=a.getParameter(a.MAX_TEXTURE_SIZE),f=Math.min(f,8192),g=b.width/b.height,e,k;e=!1;if(b.width>f||b.height>f)e=!0;else if(V())e=!0;else if(0!=(b.width&b.width-1)||0!=(b.height&b.height-1))e=!0;if(!e)return b.widthUsed=b.width,b.heightUsed=b.height,b;1<=g?(e=Math.min(b.width,f),k=e/g):(k=Math.min(b.height,f),e=k*g);c.width=d(e);c.height=d(k);a=c.getContext("2d");if(!a)return null;for(var g=e/b.width,t=0;t<b.height;t+=f)for(var i=Math.min(f,b.height-t),j=0;j<b.width;j+=f){var h=Math.min(f,b.width-
j);try{a.drawImage(b,j,t,h,i,j*g-0,t*g-0,h*g+0,i*g+0)}catch(y){return null}}c.widthUsed=e;c.heightUsed=k;return c}function g(a,b,d){b=a.createShader(b);a.shaderSource(b,d);a.compileShader(b);return!a.getShaderParameter(b,a.COMPILE_STATUS)?(console.log(a.getShaderInfoLog(b)),B=pb,null):b}function d(a){--a;for(var b=1;32>b;b<<=1)a|=a>>b;return a+1}this.ctx=this.canvas=null;var c=document.createElement("canvas");this.shAlpha=this.shMVMatrix=this.shTextureCoord=this.shVertexPos=this.shaderProg=null;this.numVertices=
0;this.mvMatrix=this.texture=null;this.initShaders=function(){var a=this.ctx,b=g(a,a.VERTEX_SHADER,"attribute vec3 aVertexPos;\nattribute vec2 aTextureCoord;\nuniform mat4 uMvMatrix;\nvarying vec2 vTextureCoord;\nvoid main(void) {\ngl_Position = uMvMatrix * vec4(aVertexPos, 1.0);\nvTextureCoord = aTextureCoord;\n}"),d=g(a,a.FRAGMENT_SHADER,"precision lowp float;\nvarying vec2 vTextureCoord;\nuniform sampler2D uSampler;\nuniform float uAlpha;\nvoid main(void) {\nvec4 textureColor = texture2D(uSampler, vTextureCoord);\ngl_FragColor = vec4(textureColor.rgb, uAlpha);\n}");
this.shaderProg=a.createProgram();a.attachShader(this.shaderProg,b);a.attachShader(this.shaderProg,d);a.linkProgram(this.shaderProg);a.getProgramParameter(this.shaderProg,a.LINK_STATUS)?(a.validateProgram(this.shaderProg),a.getProgramParameter(this.shaderProg,a.VALIDATE_STATUS)?(this.shMVMatrix=a.getUniformLocation(this.shaderProg,"uMvMatrix"),this.shAlpha=a.getUniformLocation(this.shaderProg,"uAlpha"),this.shVertexPos=a.getAttribLocation(this.shaderProg,"aVertexPos"),a.enableVertexAttribArray(this.shVertexPos),
this.shTextureCoord=a.getAttribLocation(this.shaderProg,"aTextureCoord"),a.enableVertexAttribArray(this.shTextureCoord),a.useProgram(this.shaderProg)):console.log(a.getShaderInfoLog(this.shaderProg))):console.log(a.getShaderInfoLog(this.shaderProg))};if(this.canvas=document.createElement("canvas")){try{this.ctx=this.canvas.getContext("webgl")||this.canvas.getContext("experimental-webgl")}catch(f){}this.ctx?(this.canvas.addEventListener("webglcontextlost",bd,!1),this.canvas.addEventListener("webglcontextrestored",
cd,!1),this.canvas.style.background="transparent",this.canvas.style.border="none",e.canvas.parentNode.insertBefore(this.canvas,e.canvas),this.initShaders(),this.ctx.blendFunc(this.ctx.SRC_ALPHA,this.ctx.ONE_MINUS_SRC_ALPHA),this.ctx.enable(this.ctx.BLEND),this.clearBuffers=function(){var a=this.ctx;a&&a.bindTexture(a.TEXTURE_2D,null);delete this.texture},this.setBuffers=function(){sb()?this.setCubeBuffers():this.setSphereBuffers()},this.setSphereBuffers=function(){var d=V()?b.video:b.img,c=this.ctx;
delete this.texture;if(d=a(c,d)){var f=1/b.horzFov*d.widthUsed/d.width,g=1/b.vertFov*d.heightUsed/d.height,e=d.width!=d.widthUsed,k=[],j=0,i=0,h=0,r=0,y=b.horzFov,h=Math.max(-b.vertFov/2-b.horizon,-90),H=Math.min(b.vertFov/2-b.horizon,90),D,o,l=Nb;85<=b.vertFov/2+Math.abs(b.horizon)||(l*=2);for(i=h,h=0,o=!1;!o;i+=l,h++){i>=H&&(i=H,o=!0);var m=ja(i),n=R(i),q=(H-i)*g;for(j=0,r=0,D=!1;!D;j+=l,r++){j>=y&&(j=y,D=!0);var u=ja(j),s=R(j),v=j*f;D&&e&&b.is360&&(v-=5.0E-4);k.push(new dd(v,q,u*n,m,-s*n))}}f=
[];g=[];e=null;for(y=this.numVertices=0;y<h-1;y++){e=k[y*r];f.push(e.x);f.push(e.y);f.push(e.z);g.push(0);g.push(0);this.numVertices++;for(H=0;H<r;H++)e=k[y*r+H],f.push(e.x),f.push(e.y),f.push(e.z),g.push(e.xSrc),g.push(e.ySrc),e=k[(y+1)*r+H],f.push(e.x),f.push(e.y),f.push(e.z),g.push(e.xSrc),g.push(e.ySrc),this.numVertices+=2;f.push(e.x);f.push(e.y);f.push(e.z);g.push(0);g.push(0);this.numVertices++}c.bindBuffer(c.ARRAY_BUFFER,c.createBuffer());c.bufferData(c.ARRAY_BUFFER,new Float32Array(f),c.STATIC_DRAW);
c.vertexAttribPointer(this.shVertexPos,3,c.FLOAT,!1,0,0);c.bindBuffer(c.ARRAY_BUFFER,c.createBuffer());c.bufferData(c.ARRAY_BUFFER,new Float32Array(g),c.STATIC_DRAW);c.vertexAttribPointer(this.shTextureCoord,2,c.FLOAT,!1,0,0);this.texture=c.createTexture();c.bindTexture(c.TEXTURE_2D,this.texture);try{c.texImage2D(c.TEXTURE_2D,0,c.RGBA,c.RGBA,c.UNSIGNED_BYTE,d)}catch(w){c.bindTexture(c.TEXTURE_2D,null);return}c.texParameteri(c.TEXTURE_2D,c.TEXTURE_MAG_FILTER,c.LINEAR);if(0.5>=qa&&!(85<=b.vertFov/2+
Math.abs(b.horizon))&&!V())try{c.texParameteri(c.TEXTURE_2D,c.TEXTURE_MIN_FILTER,c.LINEAR_MIPMAP_NEAREST),c.generateMipmap(c.TEXTURE_2D)}catch(A){c.texParameteri(c.TEXTURE_2D,c.TEXTURE_MIN_FILTER,c.LINEAR)}else c.texParameteri(c.TEXTURE_2D,c.TEXTURE_MIN_FILTER,c.LINEAR);c.texParameteri(c.TEXTURE_2D,c.TEXTURE_WRAP_S,c.CLAMP_TO_EDGE);c.texParameteri(c.TEXTURE_2D,c.TEXTURE_WRAP_T,c.CLAMP_TO_EDGE)}else B=Sb},this.setCubeBuffers=function(){var c=V()?b.video:b.img,d=this.ctx;delete this.texture;if(c=a(d,
c)){var f=c.widthUsed/c.width/6,e=c.heightUsed/c.height,g=1/c.width,k=0.8/c.height,f=[0,0,0,e-k,1*f,0,1*f,e-k,2*f,0,2*f,e-k,3*f,0,3*f,e-k,4*f-g,0,4*f-g,e-k,4*f-g,e-k,4*f+g,0,4*f+g,0,4*f+g,e-k,5*f-g,0,5*f-g,e-k,5*f-g,e-k,5*f+g,0,5*f+g,0,5*f+g,e-k,6*f-g,0,6*f-g,e-k];this.numVertices=22;d.bindBuffer(d.ARRAY_BUFFER,d.createBuffer());d.bufferData(d.ARRAY_BUFFER,new Float32Array([-1,1,-1,-1,-1,-1,1,1,-1,1,-1,-1,1,1,1,1,-1,1,-1,1,1,-1,-1,1,-1,1,-1,-1,-1,-1,-1,-1,-1,-1,1,1,-1,1,1,-1,1,-1,1,1,1,1,1,-1,1,1,
-1,-1,-1,-1,-1,-1,-1,-1,-1,1,1,-1,-1,1,-1,1]),d.STATIC_DRAW);d.vertexAttribPointer(this.shVertexPos,3,d.FLOAT,!1,0,0);d.bindBuffer(d.ARRAY_BUFFER,d.createBuffer());d.bufferData(d.ARRAY_BUFFER,new Float32Array(f),d.STATIC_DRAW);d.vertexAttribPointer(this.shTextureCoord,2,d.FLOAT,!1,0,0);this.texture=d.createTexture();d.bindTexture(d.TEXTURE_2D,this.texture);try{d.texImage2D(d.TEXTURE_2D,0,d.RGBA,d.RGBA,d.UNSIGNED_BYTE,c)}catch(j){d.bindTexture(d.TEXTURE_2D,null);return}d.texParameteri(d.TEXTURE_2D,
d.TEXTURE_MAG_FILTER,d.LINEAR);try{d.texParameteri(d.TEXTURE_2D,d.TEXTURE_MIN_FILTER,d.LINEAR_MIPMAP_NEAREST),d.generateMipmap(d.TEXTURE_2D)}catch(i){d.texParameteri(d.TEXTURE_2D,d.TEXTURE_MIN_FILTER,d.LINEAR)}d.texParameteri(d.TEXTURE_2D,d.TEXTURE_WRAP_S,d.CLAMP_TO_EDGE);d.texParameteri(d.TEXTURE_2D,d.TEXTURE_WRAP_T,d.CLAMP_TO_EDGE)}else B=Sb},this.paint=function(d,c,f,e){this.canvas.style.visibility="visible";var g=this.ctx;if(!g.isContextLost()){if(V()){var k=a(g,b.video);g.bindTexture(g.TEXTURE_2D,
this.texture);g.texImage2D(g.TEXTURE_2D,0,g.RGBA,g.RGBA,g.UNSIGNED_BYTE,k)}f-=d;e-=c;this.ctx.viewport(d,c,f,e);this.setMvMatrix(f,e);g.uniformMatrix4fv(this.shMVMatrix,!1,this.mvMatrix);g.uniform1f(this.shAlpha,A);g.drawArrays(g.TRIANGLE_STRIP,0,this.numVertices);h.ctx.flush();h.ctx.finish()}},this.setMvMatrix=function(a,d){var c,f=aa(a/b.width*b.horzFov/j,d/b.height*b.vertFov/j);c=2*Math.atan(f*T/2)*U;f=a/d;c=0.1*ra(c/2)/Math.sqrt(1+f*f);var g=1/1.9,f=[0.1/(c*f),0,0,0,0,0.1/c,0,0,0,0,-2.1*g,-1,
0,0,-0.4*g,0],g=u;c=R(g);g=ja(g);c=[c,0,-g,0,0,1,0,0,g,0,c,0,0,0,0,1];var e=-q,g=R(e),e=ja(e);this.mvMatrix=Lc(Lc(c,[1,0,0,0,0,g,e,0,0,-e,g,0,0,0,0,1]),f)}):delete this.canvas}}function Rc(a){function b(a){return i.x<a.x||i.x>a.x+a.cx||i.y<a.y||i.y>a.y+a.cy?!1:!0}function d(){if(!ba)return null;var a=zc(z,x);if(!a)return null;var b=t&&t.src?t.width:Tb,b=b*f(),d=t&&t.src?t.height:Tb,d=d*f();a.x-=b/2;a.y-=d/2;return 0>a.x+b||a.x>e.canvas.width||0>a.y+d||a.y>e.canvas.height?null:new Ob(a.x,a.y,b,d)}
function c(){if(!h)return null;var a=d();if(!a)return null;e.ctx.save();e.ctx.font=xa+"px "+wa;for(var b=h.split("<br>"),c=0,g=0,c=0;c<b.length;c++){var p=e.ctx.measureText(b[c]);if(p.width>g)g=p.width}e.ctx.restore();a=new Ob(a.x+1.2*a.cx,a.y+a.cy/10,g+0.8*xa,(c+0.5)*xa);b=4*f();if(0>a.x)a.x=0;else if(a.x>e.canvas.width-a.cx*b)a.x=e.canvas.width-a.cx*b;if(0>a.y)a.y=0;else if(a.y>e.canvas.height-a.cy*b)a.y=e.canvas.height-a.cy*b;return a}function f(){var a=0.2*Math.log(10*j),a=Math.max(a,0.25);return a=
Math.min(a,2)}function p(){return S?!0:!1}this.isUnderCursor=function(){var a=d();return!a?!1:b(a)};this.isPopupUnderCursor=function(){var a=c();return!a?!1:b(a)};this.gotoUrl=function(){if(S)if("_self"==k)window.location.href=S;else{var a=self.open(S,k);a&&a.focus()}};this.isLink=p;this.paint=function(){var a=d();if(a&&t)e.ctx.globalAlpha=A,e.ctx.drawImage(t,a.x,a.y,a.cx,a.cy)};this.paintPopup=function(){var a=e.ctx;a.save();a.globalAlpha=A*r;if(n)a.shadowColor="#444",a.shadowBlur=40*f(),a.shadowOffsetX=
1,a.shadowOffsetY=1;a.font=xa+"px "+wa;var b=c();if(b){a.strokeStyle=m?"#008":"transparent";a.lineWidth=m?0.5:0;var d=4*f();a.setTransform(d,0,0,d,b.x,b.y);d=e.ctx.createLinearGradient(0,0,0,b.cy);d.addColorStop(0,"#fff");d.addColorStop(1,"#ccc");a.fillStyle=d;b.x=b.y=0;Mc(a,b,2);a.shadowBlur=0;a.shadowOffsetX=0;a.shadowOffsetY=0;a.fillStyle="#008";a.textAlign="left";a.textBaseline="middle";b=h.split("<br>");for(d=0;d<b.length;d++)a.fillText(b[d],0.4*xa,xa*(d+0.7))}a.restore()};var z=a.pan?Number(a.pan):
0,x=a.tilt?Number(a.tilt):0,h=a.text?a.text:null,S=a.url?a.url:null,k=a.target?a.target:"_self";Object.defineProperty(this,"pan",{set:function(a){z=a;l()},get:function(){return z}});Object.defineProperty(this,"tilt",{set:function(a){x=a;l()},get:function(){return x}});Object.defineProperty(this,"text",{set:function(a){h=a},get:function(){return h}});Object.defineProperty(this,"url",{set:function(a){S=a},get:function(){return S}});Object.defineProperty(this,"target",{set:function(a){k=a},get:function(){return k}});
Object.defineProperty(this,"img",{get:function(){return t?t.src:null}});var t;a.img?(t=new Image,t.src=a.img):t=p()?s.imgLink:s.imgInfo;p()&&(h+="  >>");var m="boolean"==typeof a.border?a.border:s.border,n="boolean"==typeof a.shadow?a.shadow:s.shadow,r="number"==typeof a.opacity?a.opacity:s.opacity,r=N(r,0,1)}function ed(){function a(a){K();c=a;window.removeEventListener("deviceorientation",Ic,!1);window.removeEventListener("compassneedscalibration",Jc,!1);switch(a){case na:case Ja:window.addEventListener("deviceorientation",
Ic,!1),window.addEventListener("compassneedscalibration",Jc,!1)}}function b(){switch(c){case na:return"absolute";case Ja:return"relative";default:return"none"}}function d(a,b,d){this.pan=a;this.tilt=b;this.timestamp=d}Object.defineProperty(this,"mode",{set:function(b){a(b)},get:function(){return c}});Object.defineProperty(this,"isGlassMode",{get:function(){return c==na}});Object.defineProperty(this,"usrMode",{set:function(b){switch(b){case "absolute":a(na);break;case "relative":a(Ja);break;default:a(ob)}},
get:function(){return b()}});this.setListeners=function(){a(c)};this.newEvent=function(a){var b=0;if(void 0!=window.orientation)b=window.orientation;else if(void 0!=screen.mozOrientation)switch(screen.mozOrientation){case "landscape-primary":b=90;break;case "portrait-primary":b=0;break;case "landscape-secondary":b=-90;break;case "portrait-secondary":b=180}var g=0,k=0;switch(c){case na:switch(b){case 90:g=3600-a.alpha+90;Ya?g-=a.beta:90<Math.abs(a.beta)&&(g+=180);break;case 0:g=3600-a.alpha-a.gamma;
break;case -90:g=3600-a.alpha-90;Ya?g+=a.beta:90<Math.abs(a.beta)&&(g+=180);break;case 180:g=3600-a.alpha+a.gamma+180}g%=360;break;case Ja:switch(b){case 90:g=-a.beta;break;case 0:g=-a.gamma;break;case -90:g=a.beta;break;case 180:g=a.gamma}}switch(b){case 90:k=-a.gamma-90;90<Math.abs(a.beta)&&(k=Ya?-k:0<a.gamma?k+180:90);break;case 0:k=a.beta-90;-90>a.beta&&(k=90);break;case -90:k=a.gamma-90;90<Math.abs(a.beta)&&(k=Ya?-k:0>=a.gamma?k+180:90);break;case 180:k=-a.beta-90,90<a.beta&&(k=90)}if(c==na){b=
Date.now();for(a=Ya?500:100;0<f.length&&(20<=f.length||f[0].timestamp<=b-a);)f.shift();f.push(new d(g,k,b));e=j=0;for(var b=f[f.length-1],k=b.timestamp,b=b.pan,i=0,h=0,l=0,r=f.length-1;0<=r;r--){var y=f[r],H=(a-(k-y.timestamp))/a;if(0>H)break;var l=l+H,D=y.pan;-180>D-b?D+=360:180<D-b&&(D-=360);g+=360;g%=360;i+=D*H;h+=y.tilt*H}l&&(e=i/l,j=h/l)}else e=g,j=k};Object.defineProperty(this,"pan",{get:function(){return e}});Object.defineProperty(this,"tilt",{get:function(){return j}});var c=ob,f=[],e=0,j=
0}function R(a){return a?Math.cos(a*T):1}function ja(a){return Math.sin(a*T)}function ra(a){return Math.tan(a*T)}function Ta(a,b){return Math.atan2(a,b)*U}function aa(a,b){return Math.sqrt(a*a+b*b)}function N(a,b,d){return a<=b?b:a>=d?d:a}function Mc(a,b){a.beginPath();a.rect(b.x,b.y,b.cx,b.cy);a.fill();a.stroke()}function yb(a,b){this.x=a;this.y=b}function Ob(a,b,d,c){this.x=a;this.y=b;this.cx=d;this.cy=c}function fd(a,b){this.pan=a;this.tilt=b;this.yDisp=this.xDisp=0;this.valid=!1}function dd(a,
b,d,c,f){this.xSrc=a;this.ySrc=b;this.x=d;this.y=c;this.z=f}function Lc(a,b){for(var d=[],c=0,f=0,e,j,i;;){e=0;j=c;for(i=f;!(e+=a[j++]*b[i],i+=4,16<=i););d.push(e);f++;if(4==f){c+=4;if(16==c)break;f=0}}return d}pc=!1;Pb="2.2.1.19";Qb="http://www.panorado.com";mc="(c) 2012-2015 by Karl Maloszek - Simple Software";oc=!1;T=Math.PI/180;U=180/Math.PI;nb=1;w=2;ab=0;Ea=1;ma=2;ua=3;nc=3;eb=3;da=45;Ga=0.125;Ha=8;Ia=Math.SQRT2;qb=Math.sqrt(Math.sqrt(Math.sqrt(Math.SQRT2)));cb=120;db=81.8;Rb=0.04;Tb=80;xa=8;
wa="Arial,sans-serif";Y=30;Ka=20;$a=0;va=1;Fa=2;bb=3;pb=4;ob=0;na=1;Ja=2;Sb=void 0;this.about=Ub;this.reset=Vb;this.move=gb;this.moveTo=xc;this.zoom=Ca;this.zoomToCursor=function(a){M=0;K();ga=!0;P(j*a)};this.setSpeed=F;this.resize=Kc;this.selectImage=rc;this.nextImage=Yb;this.setImage=function(a){ha=null;Z=-1;X.create();Xb(a)};var Za=navigator.userAgent,Nc=navigator.platform,Oc=0<=Za.indexOf("Trident/");0<=Za.indexOf("Chrome/")&&Za.indexOf("OPR/");var Ya=0<=Za.indexOf("Firefox/");Za.indexOf("OPR/");
Nc.indexOf("Win32");var Hc=0<=Nc.indexOf("Linux")||0<=Za.indexOf("Android"),$b=640;Object.defineProperty(this,"minLivestreamWidth",{set:function(a){$b=a},get:function(){return $b}});if(Object.defineProperty)if(Object.defineProperty(this,"version",{get:function(){return Pb}}),"object"!=typeof mb)alert("PanoradoJS object constructor requires a Canvas parameter!");else{Object.defineProperty(this,"canvas",{get:function(){return e.canvas}});var Xa=!1;Object.defineProperty(this,"fullWindow",{set:function(a){Kb(a)},
get:function(){return Xa}});var kb=!0;Object.defineProperty(this,"fullWindowEnabled",{set:function(a){kb=a?!0:!1},get:function(){return kb}});var ha=null;Object.defineProperty(this,"imageList",{set:function(a){ha=a;Z=-1;X.create()},get:function(){return ha}});var Z=-1,b=null;Object.defineProperty(this,"image",{set:function(a){Z=-1;Xb(a)},get:function(){return b}});var E=null,ac=!1,wb=!1,C=nb;Object.defineProperty(this,"projection",{set:function(a){C="spherical"==a?w:nb;vb();l()},get:function(){return C==
w?"spherical":"flat"}});var gd=function(){var a=!1,b=document.createElement("canvas");if(b)try{if(b.getContext("webgl")||b.getContext("experimental-webgl"))a=!0}catch(d){}return a}();Object.defineProperty(this,"isWebGlAvailable",{get:function(){return gd}});Object.defineProperty(this,"useWebGl",{set:function(a){Cc(a)},get:function(){return h?!0:!1}});var Nb=5;Object.defineProperty(this,"gridSize",{set:function(a){Nb=N(a,1,8);vb();l()},get:function(){return Nb}});var ca=!0;Object.defineProperty(this,
"enabled",{set:function(a){ca=a?!0:!1},get:function(){return ca}});var qa=Ga,cc=Ga;Object.defineProperty(this,"minScale",{set:function(a){cc=N(a,Ga,Ha);tb();P(j)},get:function(){return cc}});var Ra=Ha,dc=Ha;Object.defineProperty(this,"maxScale",{set:function(a){dc=N(a,Ga,Ha);tb();P(j)},get:function(){return dc}});var ya=!1;if(void 0!==document.ontouchstart)try{document.createEvent("TouchEvent"),ya=!0}catch(hd){}var za=!1;if(navigator.msMaxTouchPoints)try{document.createEvent("MsPointerEvent"),za=
!0}catch(id){}Object.defineProperty(this,"isTouchAvailable",{get:function(){return ya||za}});var ea=ya||za;Object.defineProperty(this,"useTouch",{set:function(a){Ec(a)},get:function(){return ea}});var G=null;try{document.createEvent("DeviceOrientationEvent"),G=new ed}catch(jd){}Object.defineProperty(this,"isOrientationAvailable",{get:function(){return G?!0:!1}});Object.defineProperty(this,"orientationMode",{set:function(a){if(G)K(),G.usrMode=a},get:function(){return G?G.usrMode:"none"}});var ka=ya||
za;Object.defineProperty(this,"mouseMode",{set:function(a){ka="grab"==a;O()},get:function(){return ka?"grab":"pan"}});var lc=!1,kc=!1;Object.defineProperty(this,"mouseWheel",{set:function(a){lc="in"==a;kc="ignore"==a},get:function(){return kc?"ignore":lc?"in":"out"}});var Hb="",Gb="",Fb="",Eb="";Object.defineProperty(this,"panCursor0",{set:function(a){ta(a);Hb=a;O()},get:function(){return Hb}});Object.defineProperty(this,"panCursor1",{set:function(a){ta(a);Gb=a;O()},get:function(){return Gb}});Object.defineProperty(this,
"grabCursor0",{set:function(a){ta(a);Fb=a;O()},get:function(){return Fb}});Object.defineProperty(this,"grabCursor1",{set:function(a){ta(a);Eb=a;O()},get:function(){return Eb}});var Bb=2;Object.defineProperty(this,"softPan",{set:function(a){Bb=N(a,0,5)},get:function(){return Bb}});var pa=3;Object.defineProperty(this,"softZoom",{set:function(a){pa=N(a,0,5)},get:function(){return pa}});var ec=0.5;Object.defineProperty(this,"softFade",{set:function(a){ec=N(a,0,10)},get:function(){return ec}});var B=$a;
Object.defineProperty(this,"loaded",{get:function(){return v()}});var vc=!0,u=0;Object.defineProperty(this,"pan",{set:function(a){v()&&(K(),u=Pa(a),l())},get:function(){return v()?u:0}});var q=0;Object.defineProperty(this,"tilt",{set:function(a){v()&&(K(),q=Qa(a),l())},get:function(){return v()?q:0}});var j=1;Object.defineProperty(this,"scale",{set:function(a){ga=!1;P(a)},get:function(){return j}});var Sa=!1;Object.defineProperty(this,"panSpeed",{set:function(a){F(a,null)},get:function(){return v()?
m:0}});Object.defineProperty(this,"tiltSpeed",{set:function(a){F(null,a)},get:function(){return v()?n:0}});Object.defineProperty(this,"mousePan",{get:function(){return v()?Da(j,void 0,void 0,void 0,void 0).x:0}});Object.defineProperty(this,"mouseTilt",{get:function(){return v()?Da(j,void 0,void 0,void 0,void 0).y:0}});Object.defineProperty(this,"videoPlaying",{set:function(a){a?I()&&b.video.play():I()&&b.video.pause()},get:function(){return rb()}});Object.defineProperty(this,"videoSound",{set:function(a){if(I())b.video.muted=
!a},get:function(){return uc()}});Object.defineProperty(this,"videoDuration",{get:function(){return I()&&b.video.duration?b.video.duration:0}});Object.defineProperty(this,"videoCurrentTime",{set:function(a){if(I()){if(0>a)a=0;else if(a>b.video.duration)a=b.video.duration;b.video.currentTime=a;b.video.play()}},get:function(){return I()&&b.video.currentTime?b.video.currentTime:0}});var Aa=0,A=0,M=0,L=0,m=0,n=0,fa=0,W=0,fb=0,Q=0,ga=!1,la=0,Fc=0,Gc=0,Oa=null,Lb=null,lb=null,Mb=null,zb=null;Object.defineProperty(this,
"onImageLoaded",{set:function(a){Oa=a},get:function(){return Oa}});Object.defineProperty(this,"onClick",{set:function(a){Lb=a},get:function(){return Lb}});Object.defineProperty(this,"onDblClick",{set:function(a){lb=a},get:function(){return lb}});Object.defineProperty(this,"onMouseMove",{set:function(a){Mb=a},get:function(){return Mb}});Object.defineProperty(this,"onImageMove",{set:function(a){zb=a},get:function(){return zb}});var i=new function(){this.xDown=this.yDown=this.xDown1=this.yDown1=this.xDown2=
this.yDown2=this.x=this.y=this.x1=this.y1=this.x2=this.y2=null;this.time=this.startPan=this.startTilt=this.startScale=0;this.clear=function(){this.xDown=this.yDown=this.xDown1=this.yDown1=this.xDown2=this.yDown2=this.x1=this.y1=this.x2=this.y2=null;this.time=this.startPan=this.startTilt=this.startScale=0};this.setEvent=function(a){var b=parseInt(e.canvas.style.borderLeftWidth);isNaN(b)&&(b=0);var d=parseInt(e.canvas.style.borderTopWidth);isNaN(d)&&(d=0);for(var c=e.canvas,f=document.querySelector("body");c&&
c!=f;)b+=c.offsetLeft,d+=c.offsetTop,c=c.offsetParent;b-=window.pageXOffset;d-=window.pageYOffset;switch(a.type){case "mousedown":this.clear();this.startPan=u;this.startTilt=q;this.startScale=j;this.x=this.xDown=a.clientX-b;this.y=this.yDown=a.clientY-d;break;case "mouseup":this.x=a.clientX-b;this.y=a.clientY-d;break;case "mousemove":this.x=a.clientX-b;this.y=a.clientY-d;break;case "touchstart":this.clear();this.startPan=u;this.startTilt=q;this.startScale=j;2>a.touches.length?(this.x=this.xDown=a.changedTouches[0].clientX-
b,this.y=this.yDown=a.changedTouches[0].clientY-d):(this.x1=this.xDown1=a.touches[0].clientX-b,this.y1=this.yDown1=a.touches[0].clientY-d,this.x2=this.xDown2=a.touches[1].clientX-b,this.y2=this.yDown2=a.touches[1].clientY-d,this.x=this.xDown=(this.x1+this.x2)/2,this.y=this.yDown=(this.y1+this.y2)/2);break;case "touchend":case "touchmove":2>a.touches.length?(this.x=a.changedTouches[0].clientX-b,this.y=a.changedTouches[0].clientY-d):(this.x1=a.touches[0].clientX-b,this.y1=a.touches[0].clientY-d,this.x2=
a.touches[1].clientX-b,this.y2=a.touches[1].clientY-d,this.x=(this.x1+this.x2)/2,this.y=(this.y1+this.y2)/2);break;case "pointerdown":a.isPrimary?(this.clear(),this.startPan=u,this.startTilt=q,this.startScale=j,this.x1=this.xDown1=a.clientX-b,this.y1=this.yDown1=a.clientY-d,this.x=this.xDown=this.x1,this.y=this.yDown=this.y1):(this.startPan=u,this.startTilt=q,this.startScale=j,this.x2=this.xDown2=a.clientX-b,this.y2=this.yDown2=a.clientY-d,this.x=this.xDown=(this.x1+this.x2)/2,this.y=this.yDown=(this.y1+
this.y2)/2);break;case "pointerup":case "pointermove":a.isPrimary?(this.x1=a.clientX-b,this.y1=a.clientY-d,this.x=null===this.x2?this.x1:(this.x1+this.x2)/2,this.y=null===this.y2?this.y1:(this.y1+this.y2)/2):(this.x2=a.clientX-b,this.y2=a.clientY-d,this.x=(this.x1+this.x2)/2,this.y=(this.y1+this.y2)/2)}this.time=Jb(a)};this.isDragging=function(){return null!==this.xDown};this.getDragDistX=function(){return null===this.x||null===this.xDown?0:this.x-this.xDown};this.getDragDistY=function(){return null===
this.y||null===this.yDown?0:this.y-this.yDown};this.getDragDist=function(){var a=this.getDragDistX(),b=this.getDragDistY();return aa(a,b)};this.isPinchZooming=function(){return null!==this.xDown1&&null!=this.xDown2};this.getPinchScale=function(){var a=1;if(this.startScale&&null!==this.x1&&null!==this.y1&&null!==this.x2&&null!==this.y2&&null!==this.xDown1&&null!==this.yDown1&&null!==this.xDown2&&null!==this.yDown2){var b=this.x2-this.x1,d=this.y2-this.y1,c=aa(b,d),b=this.xDown2-this.xDown1,d=this.yDown2-
this.yDown1,b=aa(b,d);c/b&&(a=c/b)}return La(this.startScale*a)}},Na=!1;Object.defineProperty(this,"compassVisible",{set:function(a){Na=a;l()},get:function(){return Na}});var ba=!0;Object.defineProperty(this,"hotspotsVisible",{set:function(a){ba=a;l()},get:function(){return ba}});var s={imgInfo:Db(!1),imgLink:Db(!0),border:!1,shadow:!1,opacity:1};Object.defineProperty(this,"hotspotTemplate",{set:function(a){Yc(a)},get:function(){return s}});var $=null,oa=null,e=new function(a){function e(a,b){return a.xDisp>=
b.x&&a.xDisp<=b.x+b.cx&&a.yDisp>=b.y&&a.yDisp<=b.y+b.cy}this.arGrid=this.gridSize=this.dataUrl=this.ctx=this.canvas=null;this.useTriangles=Oc;if((this.canvas=a)&&this.canvas.getContext)if(this.ctx=a.getContext("2d")){this.canvas.setAttribute("tabindex",0);this.canvas.setAttribute("hidefocus",!0);a=this.canvas.style;a.outline="none";if(!Number(a.zIndex)||0>a.zIndex)a.zIndex=0;a.position="relative";a["-ms-touch-action"]="none";a["touch-action"]="none";a["-ms-content-zooming"]="none";a["content-zooming"]=
"none";a.background="transparent";this.canvas.addEventListener("keydown",ad);Oc&&(this.canvas.addEventListener("MSGestureTap",J),this.canvas.addEventListener("MSGestureHold",J),this.canvas.addEventListener("MSGestureStart",J),this.canvas.addEventListener("MSGestureChange",J),this.canvas.addEventListener("MSGestureEnd",J),this.canvas.addEventListener("MSGestureInertiaStart",J),this.canvas.addEventListener("MSHoldVisual",J));this.canvas.addEventListener("contextmenu",J);this.canvas.addEventListener("focus",
Zc);this.canvas.addEventListener("blur",$c);window.addEventListener("resize",jb);window.addEventListener("move",jb);this.provide2dGrid=function(){this.gridSize=Nb;this.useTriangles||(this.gridSize*=0.5);this.gridSize*=Math.min(4/Math.min(b.width/b.horzFov*j,4),2);this.gridSize=b.horzFov/Math.floor(b.horzFov/this.gridSize);var a=Math.round(b.horzFov/this.gridSize);if(b.is360)this.gridSize=b.horzFov/a;var c=Math.round(b.vertFov/this.gridSize);180>b.vertFov&&c++;a++;c++;if(!this.arGrid||this.arGrid.length!=
c)this.arGrid=Array(c);for(var f,e,g=Math.max(-b.vertFov/2-b.horizon,-90),i=Math.min(b.vertFov/2-b.horizon,90),h=0;h<c;h++){if(!this.arGrid[h]||this.arGrid[h].length!=a)this.arGrid[h]=Array(a);e=b.vertFov/2-b.horizon-h*this.gridSize;e>i?e=i:e<g&&(e=g);for(var l=0;l<a;l++)f=l*this.gridSize,this.arGrid[h][l]=new fd(f,e)}};this.update2dGrid=function(a,c,f,e){for(var g=this.arGrid.length,i=this.arGrid[0].length,h=0;h<g;h++)for(var j=0;j<i;j++){var k=this.arGrid[h][j];k.valid=!1;if(!(k.tilt<f)&&!(k.tilt>
e)){if(b.is360&&a>=c){if(k.pan<a&&k.pan>c)continue}else{if(k.pan<a)continue;if(k.pan>c)continue}var t=zc(k.pan,k.tilt);if(t)k.valid=!0,k.xDisp=t.x,k.yDisp=t.y}}};this.paintFlat=function(a,c,f,e){var g=this.ctx,h=V()?b.video:b.img;g.globalAlpha=A;g.setTransform(1,0,0,1,0,0);var i=b.width,l=b.height,k=u/b.horzFov*i,t=(0.5-(q+b.horizon)/b.vertFov)*l,m=Math.min((f-a)/j,i),l=Math.min((e-c)/j,l),k=k-m/2,t=t-l/2,m=k+m,l=t+l;0>k&&(b.is360?(k+=i,m+=i):k=0);0>t&&(t=0);if(m<=i)g.drawImage(h,Math.floor(k),Math.floor(t),
m-k,l-t,a,c,f-a,e-c);else{var n=(i-k)*j;Ya&&(n=(n+0.5).toFixed(0));g.drawImage(h,Math.floor(k),Math.floor(t),i-k,l-t,a,c,n,e-c);g.drawImage(h,0,Math.floor(t),m-i,l-t,a+n,c,f-a-n,e-c)}};this.paintSpherical=function(a,c,f,i){this.ctx.globalAlpha=A;var a=f-a,h=i-c;this.provide2dGrid();var f=hb(0,0),c=hb(0,h/2),i=hb(a/2,h/2),l=hb(a/2,-h/2),h=hb(0,-h/2);90<Math.abs(c.x-h.x)?0<f.y?(a=b.horzFov/2,f=Math.min(h.y,l.y),i=90):(a=b.horzFov/2,f=-90,i=Math.max(c.y,i.y)):(a=Math.max(i.x,l.x),f=Math.min(h.y,l.y),
i=Math.max(c.y,i.y),a+=this.gridSize);c=-a;a+=u;c+=u;b.is360&&(c=(c+3600)%360,a=(a+3600)%360);-90<f&&(f-=this.gridSize);90>i&&(i+=this.gridSize);this.update2dGrid(c,a,f,i);c=this.arGrid.length-1;i=this.arGrid[0].length-1;a=this.gridSize/b.horzFov*b.width*j;f=this.gridSize/b.vertFov*b.height*j;a=new Ob(-a,-f,this.canvas.width+2*a,this.canvas.height+2*f);for(f=0;f<c;f++)for(l=0;l<i;l++)if(h=this.arGrid[f][l],h.valid){var m=this.arGrid[f][l+1];if(m.valid){var n=this.arGrid[f+1][l+1];if(n.valid){var k=
this.arGrid[f+1][l];if(k.valid&&(e(h,a)||e(m,a)||e(n,a)||e(k,a))){var t=h.pan/b.horzFov*b.width,q=m.pan/b.horzFov*b.width;q==b.width&&q--;this.paintTile(t,(0.5-(h.tilt+b.horizon)/b.vertFov)*b.height,q,(0.5-(k.tilt+b.horizon)/b.vertFov)*b.height,h.xDisp,h.yDisp,m.xDisp,m.yDisp,n.xDisp,n.yDisp,k.xDisp,k.yDisp,0<h.tilt+b.horizon,l<i/2)}}}}};this.paintTile=function(a,b,e,g,i,h,j,l,k,m,n,q,r){this.useTriangles?(this.paintTri(a,b,e,b,e,g,i,h,j,l,k,m,!0),this.paintTri(a,b,e,g,a,g,i,h,k,m,n,q,!1)):r?this.paintTri(a,
b,e,g,a,g,i,h,k,m,n,q,!0):this.paintTri(a,b,e,b,e,g,i,h,j,l,k,m,!1)};this.paintTri=function(a,c,e,g,i,h,l,m,k,n,q,u,r){var y=this.ctx,H=a,D=c,o=e-a,v=h-c,s,e=e-a,g=g-c,i=i-a,h=h-c,a=c=0,k=k-l,n=n-m,q=q-l,u=u-m,w=i*g-e*h,B=(q*g-k*h)/w,C=(u*g-n*h)/w,k=(k*i-q*e)/w,n=(n*i-u*e)/w;y.save();y.setTransform(B,C,k,n,l,m);this.useTriangles&&(y.beginPath(),s=1==A?1:0,r?(y.moveTo(a-2*s,c-s),y.lineTo(e+s,g-s),y.lineTo(i+s,h+2*s)):(y.moveTo(a-s,c-2*s),y.lineTo(e+2*s,g+s),y.lineTo(i-s,h+s)),y.closePath(),y.clip());
try{var E=V()?b.video:b.img;s=1==A?10/j/this.gridSize:0;o=Math.min(o+s,b.width-H);v=Math.min(v+s,b.height-D);y.drawImage(E,H,D,o,v,0,0,o,v)}catch(F){}y.restore()}}}(mb),h=new Dc;if(!h.canvas||!h.ctx)h=null;Ec(ea);var X=new function(){function a(){if(e.canvas){r=[];var a=e.ctx,c=1.1*Y*d,D=1.5*Y*d,o=10+c/2;f&&(r.push({x:o,fnPaint:function(){a.beginPath();a.moveTo(-4,-4);a.lineTo(4,0);a.lineTo(-4,4);a.closePath();a.stroke()},fnClick:function(){Vb()}}),o+=D);h&&I()&&(r.push({x:o,fnPaint:function(){a.beginPath();
a.arc(0,0,7,0,2*Math.PI,!0);rb()?(a.moveTo(-2,-3),a.lineTo(-2,3),a.moveTo(2,-3),a.lineTo(2,3)):(a.moveTo(-2,-2),a.lineTo(2,0),a.lineTo(-2,2),a.closePath(),a.stroke());a.stroke()},fnClick:function(){tc()}}),o=o+c+Y*d,r.push({x:o,xFactor:3,fnPaint:function(){var c=I()&&b.video.duration?b.video.currentTime/b.video.duration:0;a.fillStyle="rgba(196, 196, 255, 0.6)";a.fillRect(-44,-9,88*c,18);if(I())var c=b.video.currentTime,d=b.video.duration,c=ib(Math.floor(c/60),2)+":"+ib(Math.floor(c%60),2)+" / "+ib(Math.floor(d/
60),2)+":"+ib(Math.floor(d%60),2);else c=0;a.font="12px "+wa;a.textAlign="center";a.textBaseline="alphabetic";a.fillStyle="rgba(255,255,255,1)";a.fillText(c,0,4)},fnClick:function(){var a=3*Y*d,c=r[g()].x-a/2,a=(i.x-c)/a;if(I()&&b.video.duration)b.video.currentTime=b.video.duration*a,b.video.play()}}),o=o+c+Y*d,r.push({x:o,fnPaint:function(){a.beginPath();a.moveTo(-7,2);a.lineTo(-4,2);a.lineTo(0,5);a.lineTo(0,-5);a.lineTo(-4,-2);a.lineTo(-7,-2);a.closePath();a.stroke();a.lineWidth=1.7;a.beginPath();
a.arc(0,0,4,-0.8,0.8);a.stroke();a.beginPath();a.arc(0,0,7.5,-0.8,0.8);a.stroke();if(uc())a.lineWidth=1.5,a.moveTo(-8,7),a.lineTo(8,-7),a.moveTo(8,7),a.lineTo(-8,-7);a.stroke()},fnClick:function(){if(I())b.video.muted=!b.video.muted}}),o+=D);q&&(r.push({x:o,fnPaint:function(){a.beginPath();a.moveTo(-4,0);a.lineTo(4,0);a.stroke()},fnClick:function(){Ca(1/Ia)},fnEnabled:function(){return j>qa}}),o+=c,r.push({x:o,fnPaint:function(){a.beginPath();a.moveTo(-4,-1);a.lineTo(0,-4);a.lineTo(0,6);a.stroke()},
fnClick:function(){P(1)},fnHilight:function(){return 1==j}}),o+=c,r.push({x:o,fnPaint:function(){a.beginPath();a.strokeRect(-4,-4,8,8)},fnClick:function(){Sa?Sa=!1:P(0)},fnHilight:function(){return Sa}}),o+=c,r.push({x:o,fnPaint:function(){a.beginPath();a.moveTo(-4,0);a.lineTo(4,0);a.moveTo(0,-4);a.lineTo(0,4);a.stroke()},fnClick:function(){Ca(Ia)},fnEnabled:function(){return j<Ra}}),o+=D);s&&(r.push({x:o,fnPaint:function(){a.beginPath();a.moveTo(3,-3);a.lineTo(-3,0);a.lineTo(3,3);a.stroke()},fnClick:function(){F(m-
2,null)}}),o+=c,r.push({x:o,fnPaint:function(){a.beginPath();a.moveTo(-3,-4);a.lineTo(-3,4);a.moveTo(3,-4);a.lineTo(3,4);a.stroke()},fnClick:function(){F(0,0)},fnEnabled:function(){return 0!=m||0!=n}}),o+=c,r.push({x:o,fnPaint:function(){a.beginPath();a.moveTo(-3,-3);a.lineTo(3,0);a.lineTo(-3,3);a.stroke()},fnClick:function(){F(m+2,null)}}),o+=D);u&&ha&&(r.push({x:o,fnPaint:function(){a.beginPath();a.moveTo(-3,-3);a.lineTo(-9,0);a.lineTo(-3,3);a.stroke();a.strokeRect(1,-4,8,8)},fnClick:function(){Yb(-1)},
fnEnabled:function(){return 0<Z}}),o+=c,r.push({x:o,fnPaint:function(){a.beginPath();a.moveTo(3,-3);a.lineTo(9,0);a.lineTo(3,3);a.stroke();a.strokeRect(-9,-4,8,8)},fnClick:function(){Yb(1)},fnEnabled:function(){return Z<ha.length-1}}),o+=D);v&&$&&(r.push({x:o,fnPaint:function(){a.beginPath();a.arc(0,0,4,0,2*Math.PI,!0);a.moveTo(-7,0);a.lineTo(7,0);a.moveTo(0,-7);a.lineTo(0,7);a.stroke()},fnClick:function(){ba=!ba;l()},fnHilight:function(){return ba}}),o+=c);k&&kb&&(r.push({x:o,fnPaint:function(){a.beginPath();
a.moveTo(-8,2);a.lineTo(-8,6);a.lineTo(-5,6);a.moveTo(8,2);a.lineTo(8,6);a.lineTo(5,6);a.moveTo(-8,-2);a.lineTo(-8,-6);a.lineTo(-5,-6);a.moveTo(8,-2);a.lineTo(8,-6);a.lineTo(5,-6);a.stroke()},fnClick:function(){Kb(!Xa)},fnHilight:function(){return Xa}}),o+=c);t&&(r.push({x:o,fnPaint:function(){a.fillStyle=a.strokeStyle;a.font="bold 16px "+wa;a.textAlign="center";a.textBaseline="alphabetic";a.fillText("?",0,6)},fnClick:function(){"javascript:"==t.substr(0,11).toLowerCase()?eval(t.substr(11)):(w=self.open(t,
"ViewerHelp","width=500,height=600,location=no,menubar=no,scrollbars=no,resizable=yes,status=no,toolbar=no,titlebar=yes"))&&w.focus()}}),o+=c);r.push({x:o,fnPaint:function(){a.beginPath();a.moveTo(-3,-1);a.lineTo(0,-1);a.lineTo(0,5);a.moveTo(-4,5);a.lineTo(4,5);a.stroke();a.beginPath();a.arc(-0.5,-5,0.7,0,2*Math.PI,!0);a.stroke()},fnClick:function(){Ub()}});A&&self.opener&&r.push({x:o+c,fnPaint:function(){a.beginPath();a.moveTo(0,-7);a.lineTo(0,3);a.stroke();a.beginPath();a.arc(0,1,5,225*Math.PI/
180,315*Math.PI/180,!0);a.stroke()},fnClick:function(){w&&!w.closed&&(w.close(),w=null);window.close()}})}}function g(){if(!hc()||!r||document.activeElement!=e.canvas)return-1;var a=Y*d/2,b=Ka*d/2,c=e.canvas.height-10-b;if(!(i.y>=c-b&&i.y<=c+b))return-1;for(b=0;b<r.length;b++){var c=r[b],f=c.xFactor?c.xFactor:1;if(i.x>=c.x-a*f&&i.x<=c.x+a*f)return b}return-1}this.getFunctionUnderCursor=function(){if(!hc()||!r)return null;var a=Y*d/2,b=Ka*d/2,c=e.canvas.height-10-b;if(!(i.y>=c-b&&i.y<=c+b))return null;
for(b=0;b<r.length;b++){var c=r[b],f=c.xFactor?c.xFactor:1;if(i.x>=c.x-a*f&&i.x<=c.x+a*f)return c.fnEnabled?c.fnEnabled()?c.fnClick:!1:c.fnClick}return null};this.mouseOver=g;this.paint=function(){if(r){var a=e.ctx;a.save();a.globalAlpha=1;a.strokeStyle="#fff";for(var b=e.canvas.height-10-Ka*d/2,c=0;c<r.length;c++){var f=r[c],g=f.x,h=f.xFactor?f.xFactor:1,i=!f.fnEnabled||f.fnEnabled();a.setTransform(d,0,0,d,g,b);a.fillStyle=f.fnHilight&&f.fnHilight()?"rgba(64, 85, 127, 0.6)":"rgba(12, 16, 24, 0.6)";
a.lineWidth=i?1.5:0.5;a.strokeStyle="#fff";g=new Ob(-Y/2*h,-Ka/2,Y*h,Ka);Mc(a,g,3);a.lineWidth=2;a.strokeStyle=i?"#fff":"#aaa";f.fnPaint()}a.restore()}};this.create=a;var d=1;Object.defineProperty(this,"size",{set:function(a){d=N(a,0.7,2);X.create()},get:function(){return d}});var c=!0,f=!0,h=!0,q=!0,s=!0,u=!0,v=!0,k=!0,t="",w=null,A=!0;Object.defineProperty(this,"visible",{set:function(a){c=a;l()},get:function(){return c}});Object.defineProperty(this,"reset",{set:function(b){f=b;a()},get:function(){return f}});
Object.defineProperty(this,"video",{set:function(b){h=b;a()},get:function(){return h}});Object.defineProperty(this,"scale",{set:function(b){q=b;a()},get:function(){return q}});Object.defineProperty(this,"motion",{set:function(b){s=b;a()},get:function(){return s}});Object.defineProperty(this,"hotspots",{set:function(b){v=b;a()},get:function(){return v}});Object.defineProperty(this,"fullWindow",{set:function(b){k=b;a()},get:function(){return k}});Object.defineProperty(this,"browse",{set:function(b){u=
b;a()},get:function(){return u}});Object.defineProperty(this,"helpUrl",{set:function(b){t=b;a()},get:function(){return t}});Object.defineProperty(this,"closeWindow",{set:function(b){A=b;a()},get:function(){return A}});var r=null;a()};this.controls=X;var fc=!1,gc=-1;X.create();ta(Hb);ta(Gb);ta(Fb);ta(Eb);jb();l();O();setTimeout(function(){try{var a=new Image;a.onload=function(){alert("Panorado JS viewer can't be used from this location!");e=void 0};a.onerror=function(){};a.src=Qb+"/pjscount.php?"+
Date.now()}catch(b){}},1E4)}else alert("PanoradoJS requires a browser with ECMAScript 5 support! Hint: Prevent compatibility mode in MSIE!")};